### ISSUE TITLE
Use of GETDATE

### ISSUE THREAD

**Issue by londondba** [JocaPC/qpi#1]
I see the code uses GETDATE. Would it not be better to use GETUTCDATE instead ? That way you are safe from daylight saving time issues.

**Comment by JocaPC** [comment]
Thanks for reporting this and you are right.
I have initially implemented this for Azure SQL DB that is in UTC timezone, so I didn't noticed the difference. There are some views that return the wrong results because GETDATE is used instead of GETUTCDATE on on-prem SQL Server.

I have updated the script to use GETUTCDATE, however in some cases I still need to use GETDATE like in sys.dm_exec_requests that uses local time and not utc time.

**Comment by JocaPC** [comment]
I'm closing this issue because I have changed all necessary parts. Let me know if you find some additional change that should be made. 

I'm keeping `GETDATE` in the following cases:
- `dm_bre` because the underlying view returns data in local time zone so `GETDATE` is needed for comparison.
- On the places where I generate default title based on local time.

Thanks
