### ISSUE TITLE
Issue with Azure SQL

### ISSUE THREAD

**Issue by markgould** [JocaPC/qpi#3]
I'm attempting to use the Azure SQL (non-managed) script and I'm getting an error:

> Invalid object name 'sys.master_files'.

This is not supported in Azure SQL - is there a workaround available?

**Comment by JocaPC** [comment]
Hi, make sure that you are using the script for Azure SQL Database version. I see that is this version the view `sys.recommendations` uses `master_files` and I will remove this. Other functions should work fine. Note that QPI for single database has reduced functionalities because some underlying views are not supported.

**Comment by JocaPC** [comment]
@markgould could you try the latest version?

**Comment by markgould** [comment]
That worked, thanks for the quick fix!
